evilew/GS13

code/modules/research/designs/biogenerator_designs.dm

coppied the entry for milk, changed 'milk' to 'flour' and upped the ammout produced to 15u (flour is not very nutritious) (also 15u is used for all recipies).
I hope I did this right.
add: Added flour to the biogenerator
I keep running out of flour in the kitchen
:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

Added flour and I did it all myself :)

---

modular_citadel/code/modules/arousal/organs/genitals.dm

Fixed Genitals Disapering

---

modular_citadel/code/modules/arousal/organs/genitals.dm

I fixed the fuck up I made when I tried to fix my fuck up.

Fixed the Fix

---

code/datums/traits/neutral.dm

Added a "Universal diet" quirk. Picked through the quirks menu during character creation. The character spawns with the trait with no food dislikes, can eat anything normally edible without nausea.
I can finally fatten up my lizard MILF with whatever I want, ha-ha.
:cl:
add: Added a "Universal diet" quirk. Eat whatever you want as whoever you want!
/:cl:

Adds a "Universal diet" quirk.

---

_maps/RandomRuins/LavaRuins/lavaland_surface_snack_store.dmm
code/datums/ruins/lavaland.dm
config/lavaRuinBlacklist.txt

Thought I'd do a quick merge to prevent conflicts in the lavaland ruin file.

new lavaland ruin (snack store)

---

code/datums/diseases/advance/symptoms/species.dm
code/modules/antagonists/disease/disease_abilities.dm

I forgor 💀 
Forgot to include the robotic adaptation symptom in the last pull request (forgot to commit it to the branch specifically)
So that's what this is.
Think it also add necrotic metabolism for sentient virus. Wasn't there for some obscure reason.
Still to allow more people to peruse the mechanic despite race preference.
:cl:
add: necrotic metabolism for sentient viruses
tweak: the robotic_adaptation (electronic propagation) symptom is actually there now
/:cl:

New Symptom

---

.vscode/launch.json
GainStation13/code/mobs/unusualtentical.dm
GainStation13/code/modules/mob/living/emote.dm
GainStation13/code/modules/reagents/chemistry/reagents/consumable_reagents.dm
GainStation13/code/modules/vending/gatocola.dm
GainStation13/code/modules/vending/mealdor.dm
code/modules/antagonists/nukeop/equipment/nuclearbomb.dm

Cleans up a lot of the issues that I found inside of the GS13 files. 
a few bugs that this should potentially fix should be:
- GS13 specific emotes still working for non-humans 
- Lipoifier not processing inside of people with the `LIPOIFIER_IMMUNE_TRAIT` trait. (It still won't affect them.)
- Multiple warnings upon compiling
I also added an option in the launch.json to launch from Dream Daemon instead of just from DreamSeeker. 
This should fix a few bugs along with making future development work easier. 
:cl:
code: Adds in a Dream Daemon launch option for Visual Studio Code
fix: GS13 specific emotes no longer work on non-humans
fix: Lipoifier now processes, but does not apply weight gain, for mobs with the lipoifier immune trait. 
/:cl:

GS13 Code cleanup

---

code/datums/weather/weather_types/layenia.dm
hyperstation/code/datums/weather/oxygen_rain.dm

Comments out the Hyperstation station storms.
We use standard space stations, so having the text appear just feels odd
:cl:
del: Storms from Hyperstation no longer trigger. 
/:cl:

Removes HS13 Storms

---

GainStation13/code/mechanics/fatness.dm
code/modules/mining/lavaland/ruins/gym.dm

When using the weights or punching bag, assuming that the user is a human, the user will lose weight.
More ways to lose weight besides chems is good.
:cl:
add: Gym equipment now helps burn off weight.
/:cl:

Using the gym equipment now makes you lose weight

---

code/modules/antagonists/nukeop/equipment/nuclearbomb.dm
code/modules/food_and_drinks/recipes/tablecraft/recipes_cake.dm
code/modules/projectiles/projectile/magic.dm

never do a PR with code that's spitting out errors

tiny little PR to fix someone's goofiness

---

modular_citadel/code/modules/mob/dead/new_player/sprite_accessories.dm

There is more than enough Sharknet for everyone to share, because of this, the Sharknet markings are now being non-ckey locked.
(I have permission to do this.)
more markings available are a good thing.
:cl:
config: datashark markings are no longer ckey locked
/:cl:

DEMOCRATIZES SHARKNET

---

GainStation13/code/mechanics/spells.dm

Makes the weight gain/transfer spells 3 times as potent. 
The spells have a long charge time but don't have much of an impact right now
:cl:
balance: makes the weight gain spells 3 times as effective.
/:cl:

Buffs the effectiveness of the weight gain spells

---

GainStation13/code/mechanics/fatness.dm
GainStation13/code/modules/client/preferences/preferences.dm
code/modules/client/preferences.dm
code/modules/client/preferences_savefile.dm

Adds in a new maximum weight pref, allowing the user to chose the maximum weight they can get up to.
Giving players more control over how they interact with weight gain mechanics is good.
:cl:
add: Adds in a new pref for maximum weight.
/:cl:

Max Weight Pref

---

GainStation13/code/mobs/cakegolem.dm

Fixes the cake golem not being able to be eaten
Fix good :3
:cl:
fix: cake golems can now be eaten again.
/:cl:

Fixes cake golem being not able to be eaten

---

code/modules/reagents/chemistry/reagents/toxin_reagents.dm

tweaks mint toxin to gib people more consistently by only gibbing people with TRAIT_BLOB.

Mister Mann's mint toxin update! (RUN FATTIES)

---

GainStation13/code/modules/mob/living/emote.dm
code/__DEFINES/mobs.dm
code/modules/mob/mob_defines.dm

I added fullness reduction to burp, belch, fart, and brap. I also added a new belly rub emote that also reduces fullness
Adds a different way to reduce fullness for more rp opportunities, if the changes seem too strong it's easy to change the settings.
:cl: Fed09022
add: Fullness reduction to burp, belch, fart, and brap emotes
add: New emote: bellyrub which also reduces fullness
/:cl:

Emote fullness reduction

---

GainStation13/code/mobs/races/caloritegolem.dm
code/__DEFINES/food.dm
code/modules/food_and_drinks/food.dm

Remove BLESSED foodtype.
Add blessed flag.
Use blessed flag instead of foodtype.
`foodtype` is a bitfield, and should not be assigned without bitwise operators.
:cl: psq95
fix: calorite golem bless action
/:cl:

Fix calorite golem

---

code/modules/atmospherics/machinery/pipes/pipes.dm

Add null checks to pipes.dm
Reduce log spam
:cl: psq95
server: reduce log spam from broken pipes
/:cl:

Add null checks to pipes.dm

---

code/modules/mob/living/carbon/life.dm

Do not poke data_core if SSD
Attempt to fix lag induced by looping over players when one goes SSD
:cl: psq95
fix: status in crew manifest
/:cl:

Do not poke data_core if SSD

---

modular_citadel/code/modules/reagents/chemistry/reagents/enlargement.dm

Do not touch organs unless transitioning.
Some female characters have breasts but no vagina or womb and do not wish to gain these organs. The same behaviour should apply to transitioning male characters.
:cl: psq95
tweak: enlarger OD
/:cl:

Tweak enlarger overdose process

---

code/__HELPERS/global_lists.dm
code/modules/client/preferences.dm

added: Strawberry milk as an option in customization for lactation and cum options.
/:cl:

Strawberry milk

---

_maps/map_files/KiloStation/KiloStation.dmm

:cl:
add: Replaced the fight room with a pool and exercising equipment.
add: Added a crashed calorite pod to the map.
/:cl:

Kilo station changes

---

code/modules/reagents/chemistry/machinery/chem_dispenser.dm

I changed the soda dispenser reagents list to pull the correct kind of tea.
Because now we can get Tea from dispensers.
:cl:
fix: The tea button now dispenses tea
/:cl:

Tea Button Fix

---

code/controllers/subsystem/dbcore.dm

Add filter for INET_ATON to BSQL_DEBUG messages.
Player's IP addresses should not be leaked in logs.
:cl: psq95
server: new filter for SQL log
/:cl:

Strip sensitive information from SQL log

---

code/__HELPERS/_lists.dm
code/controllers/configuration/entries/general.dm
code/modules/admin/admin.dm
code/modules/admin/admin_verbs.dm
code/modules/client/border_control.dm
code/modules/client/client_procs.dm
config/config.txt
tgstation.dme

Finally adding some form of filter to prevent people who havent been manually greenlit to join. Maybe to hopefully make going on the hub a more viable option
:cl:
add: Added new things
add: Added more things
fix: fixed a few things
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

Time to Build a Wall, a BORDER WALL

---

GainStation13/code/mechanics/fatness.dm
GainStation13/code/mechanics/spells.dm
code/modules/client/preferences.dm
code/modules/reagents/chemistry/reagents/toxin_reagents.dm
modular_citadel/code/modules/vore/eating/bellymodes_vr.dm

Changed realfatness into fatness_real and overfatness into fatness_over

Variable name changes

---

GainStation13/code/modules/clothing/under/jobs/modcivilian.dm

- Temporary fix for organ sizes going past the maximum breaking clothes sprite overlays

Temporary modular clothes max size fix

---

GainStation13/code/modules/clothing/under/jobs/modcivilian.dm
modular_citadel/code/modules/arousal/organs/genitals.dm

-Icon of the modclothes overlays now specificed as a variable
-Mod clothes breasts overlays code changed to better handle the unique way in which breast sizes are picked
-Genitals update lag fixed (hopefully)
-Added comments for modular clothes sprites
SOMEONE PLEASE WORK ON THE LAYER ON WHICH THE OVERLAYS ARE DRAWN I BEG YOU

Modular clothes breast fixes

---

_maps/map_files/KiloStation/KiloStation.dmm

So while this doesnt exactly FIX the code in general, this however stops what the loops are starting on. Any and all 'barricaded' doors have since been welded shut instead. Better bring a welder!
... Less lag is good, right?
:cl:
del: Removed old things
tweak: tweaked a few things
fix: fixed a few things
/:cl:

Doorfix, Plz Gib.

---

GainStation13/code/modules/clothing/under/jobs/modcivilian.dm

Adds if to check if the clothes' user exists, to avoid null user errors

Modclothes null user fix

---

code/__DEFINES/traits.dm
code/modules/mob/living/carbon/human/species.dm
code/modules/surgery/organs/vocal_cords.dm
hyperstation/code/datums/traits/neutral.dm
modular_citadel/code/datums/traits/neutral.dm

It's a pretty simple one. It removes the named traits.
Reduces awkwardness in GS13. Risking 90% awkwardness for 10% comedy is a bit foolish.
:cl:
del: Removing masochism and Virile traits.
/:cl:

Removing masochism and Virile traits.

---

code/modules/mob/living/carbon/human/species.dm
code/modules/surgery/organs/vocal_cords.dm

Mostly correcting errors in regard to removing traits. It does show a massive failure if PRs are going to be merged without checking for compilation errors first.
It allows the game to be compiled? Seriously!
:cl:
tweak: Adjusted and removed parts from removing mascho trait.
/:cl:

Fixing compilation errors related to removing traits.

---

GainStation13/code/datums/mutations/fatfang.dm

Nibbe mutation ability now injects the amount specified by the chem_to_add variable

Small Nibble fix

---

GainStation13/code/datums/mutations/fatfang.dm
GainStation13/code/mechanics/web_weaving.dm
code/__DEFINES/traits.dm
code/__HELPERS/global_lists.dm
code/game/objects/effects/spiders.dm
code/modules/client/preferences.dm
code/modules/reagents/chemistry/reagents/drink_reagents.dm
hyperstation/code/modules/arousal/arousalhud.dm

Web Weaver quirk now also adds an action to spin sticky webs where you stand.
Characters with the Web Weaver quirk can freely move through webs.
Added nutriment as an option for fluid for genitals
Adds an option in the arousal menu to feed a character pulled by the user with the reagents of a chosen genital and options in the arousal menu to feed yourself using your own organs or that of others you are pulling
The Nibble now pumps venom over time if used against character you are pulling, now affected by chromosomes
Milk now has a nutriment factor

Web Weaver Webs, Genital Feeding, Genital Nutriment, Milk nutriment

---

GainStation13/code/machinery/adipoelectric_generator.dm
GainStation13/code/machinery/adipoelectric_transformer.dm
code/modules/research/techweb/all_nodes.dm
tgstation.dme

Added the adipoelectric generator, a machine that takes fat from the person who uses it and turns into current for the wire it's placed on. Unlocked at roundstart
Internal cleanup for the adipoelectric transformer

Adipoelectric Generator

---

hyperstation/code/modules/clothing/sizeaccessories.dm

QOL fix that makes normalizer collars small items so you can stick em in boxes and not eat the entirety of your backpack space to take off. Epic gaming
makes shit convinient to use. I added one line of codegus
:cl:
add: one line of code to sizeaccessories.dm
tweak: Made normalizer neckwear small sized items from normal sized items. QOL.
/:cl:

Makes normalizer collars small sized items

---

code/game/machinery/harvester.dm

I ported this directly from yog station
rotate
:cl:
add: organ harvester rotation
/:cl:

Makes organ harvesters rotatable

---

GainStation13/code/modules/mob/living/emote_ported.dm
code/modules/mob/living/carbon/human/species_types/humans.dm
modular_citadel/code/modules/mob/living/carbon/human/species_types/furrypeople.dm

not me!!!
It makes the game compile, which is needed to run the game
:cl:
fix: Fixed bad code from my ports oops
/:cl:

Who is testing

---

GainStation13/code/machinery/adipoelectric_generator.dm

Fix for the null occupant error of the adipoelectric generator. Added appropriate process kill, stop and start

Adipoelectric Generator fix

---

GainStation13/code/datums/diseases/advance/symptoms/berry.dm
GainStation13/code/modules/client/preferences/preferences.dm
code/__HELPERS/global_lists.dm
code/modules/client/preferences.dm
code/modules/client/preferences_savefile.dm
tgstation.dme

Added "infectious" blueberry juice, which makes you swell depending on how much you have inside of you (also turns you blue). While you have some inside, clicking on yourself with a beaker will juice up to 10 out of you
Added this juice as an option for genitals fluid
Added Berrification virus, which makes you produce juice. It is a level 7 virus. It can be cured through normal virology means or by getting all infected juice out of the person
Added a "Blueberry Inflation" preference (juice will disappear when inside you, virus will not make you produce)

Blueberry Virus

---

GainStation13/code/modules/reagents/chemistry/reagents/consumable_reagents.dm

Fixed issues the Blueberry Inflation preference

Blueberry Pref fix

---

GainStation13/code/datums/diseases/advance/symptoms/berry.dm
GainStation13/code/modules/reagents/chemistry/reagents/consumable_reagents.dm

Blueberry stains now generate randomly when a character is "juiced", not over time while a character has some in them

 Blueberry stains change

---

GainStation13/code/mechanics/web_weaving.dm

Does at the title says
It feels a bit weird seeing a big mob being made small after being cocooned.
:cl:
tweak: web weaving cocoons now scale with size
/:cl:

Web weaving cocoons now scale with target mob size

---

code/game/machinery/cloning.dm
code/game/machinery/computer/cloning.dm

does as the title says
Enables fun weight gain shenanigans, like threatening to clone scan someone after they are fat. 
:cl:
add: cloning now keeps fatness
/:cl:

cloning now keeps fatness

---

code/modules/mob/living/carbon/human/species.dm

Does as the title says
fix good :)
:cl:
fix: Fixes helplesness prefs not disabling when pref set to none
/:cl:

Fixes helplesness prefs not disabling when pref set to none

---

code/datums/components/crafting/recipes/recipes_misc.dm

Exactly what it says on the tin.
Because big muscle (I've wanted crafting recipes for these for quite a bit)
:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

Add Exercise Equipment Crafting Recipes

---

GainStation13/code/modules/mob/living/emote.dm

It logs the biblefarting and also fixes a minor gramatical error
:cl:
spellcheck: "Divine" not "Devine"
admin: Added logging to the bible fart
/:cl:

Fixes a typo in the biblefart notification and also adds logging to it

---

GainStation13/code/modules/gym/gym.dm
GainStation13/code/modules/hydroponics/munchies_weed.dm

Changed dumbbell chat messages to only appear for the user.
Fixed grammatical errors in appetite stimulant

Misc fixes

---

code/modules/mob/living/carbon/human/species.dm

Fixes limb paralysis and nearsighted with the helplessness prefs not properly working
bug fix good :3
:cl:
fix: Fixes limb paralysis and nearsighted with the helplessness prefs not properly working
/:cl:

helplessness fixes

---

code/modules/mob/living/living_movement.dm
config/game_options.txt

Increases the default move speed.
Things feel slow and clunky, this should help the game feel better to play.
:cl:
config: Reduces the move delay while walking from 1.3 to 1.1
/:cl:

Increases move speed

---

code/modules/mob/dead/new_player/new_player.dm

does as the title says, if you don't have OOC notes, you can't join.
This is a server where communication is important. If you want to play on here, you need to communicate with others what you are and aren't okay with.
:cl:
server: players can no longer join the game without OOC notes.
/:cl:

makes ooc notes mandatory

---

code/game/objects/items/cards_ids.dm

Makes the Captain's ID Card orbitable
This should make it easier for people to track down the spare whenever it is taken somewhere where it shouldn't be. We are a low-pop server, and playing without the spare is a pain in the ass.
:cl:
config: Makes the Captain's ID Card orbitable
/:cl:

Makes the Captain's ID Card orbitable

---

GainStation13/code/datums/mutations/radfat.dm
code/__DEFINES/DNA.dm
code/__DEFINES/misc.dm
tgstation.dme

Added the Radiotrophic Metabolism mutation, makes a character gain fat over time (stronger if they are irradiated) and become immune to the adverse effects of radiations

Radiotrophic Metabolism mutation

---

GainStation13/code/mechanics/fatrousal.dm
code/__DEFINES/traits.dm
tgstation.dme

Adds the Adiposexual Response quirk . Characters gain fatness as they gain arousal and lose it when it goes down

Adiposexual Response

---

GainStation13/code/modules/reagents/chemistry/recipes/fatchem.dm

Changed the sugar requirement for lipoifier to caramel to prevent conflicts with the synthtissue recipe

Lipoifier recipe change

---

GainStation13/code/game/sound.dm
code/game/objects/items/RCD.dm
code/game/objects/items/RPD.dm
code/game/objects/items/storage/belt.dm
yogstation/code/game/objects/items/tools.dm

The real poopwater PR is Reo's inability to code without introducing at least 1 bug or error
The real poopwater PR is Reo's inability to code without introducing at least 1 bug or error
Im going to submit this before I make more changes that inevitably break something again.
Fixes a bunch of stuff. You dont need to hear farts anymore, yippie
:cl:
add: Added new things
add: Added more things
del: Removed old things
balance: rebalanced Hand Drill Speed from `.25` to `.35`. Also fixes the speed unintentionally being `.7`
balance: rebalanced Jaws of Life Speed from `.25` to `.35`. Also fixes the speed unintentionally being `.7`
balance: rebalanced something
fix: fixed burp and fart sounds not respecting prefs.
fix: toolbelts being unable to hold RCDs.
fix: durathread toobelts being unable to …

Minor Fixes
