evilew/GS13

- code/datums/traits/neutral.dm
Allows a player to select a quirk that spawns them with a wheelchair.
At least one person has directly requested this quirk and I beleve a few other people may be interested in using it.
The quirk is neutral and costs 0 points, it can be found under movement quirks, called Mobility Assistance.
on_spawn() code coppied from the parapalegic quirk.
> Spawn With Wheelchair Quirk

- modular_citadel/code/modules/mob/living/silicon/robot/robot_modules.dm
Adds the "Fat" cyborg modules to the list of available cyborg appearances for the following cyborg types: Engineering, Mining, Security, Medical, Service and Peacekeeper. They appear on the selection wheel correctly and are correctly applied to cyborgs.
Sprites themselves NOT MADE BY ME, they were already provided in the game files, made by Agent Legit 22#8403 on Discord.
Fat cyborgs. What is not to love?
:cl:
add: Added fat cyborgs.
/:cl:
> Fat cyborgs.

- code/modules/client/preferences.dm
- code/modules/mob/living/carbon/human/species.dm
Fixed a spelling error in the start fatness input window.
Commented the fatness conversion code to point out a coding oversight.
> Spelling error and code comment

- _maps/map_files/BoxStation/BoxStation.dmm
One of the privacy shutters on the med break room had the wrong ID.
This is now fixed.
> Med privacy fix

- disease_abilities.dm
- weight.dm
This adds a weight gain symptom to the list of available symptoms. Weight gain causes its victims to gain weight, with the amount gained per time the virus triggers scaling depending on how transmissible it is. 
This pull also contains an update to how the weight loss symptom works, which now reduces the victim's fatness level per trigger.
Finally, this pull also makes weight gain compatible with the sentient disease antagonist, along with some balance changes to sentient disease to allow weight gain (and some other symptoms) to be used on lowpop rounds
These changes will benefit the game because it may provide incentive for people to play as a virologist more often, as few choose it over other roles on the server.
:cl:
add: Added weight gain symptom
add: Added weight gain symptom as an …
> Weight gain virus stuff

- code/datums/diseases/advance/advance.dm
- code/datums/diseases/advance/presets.dm
- code/modules/events/disease_outbreak.dm
Tweaks a few virus things, most notably the requirements for transmission types. Other changes include :
- one of the max resistance cure changed form bicaridine (come on) to krokodil.
- fixing the admin virus creation to notably properly change infectable biotypes (races).
- limiting the event that gave too many symptoms to 8 max. 
- I have also decided to add a symptom that specifically allows the infection of robotic races. 
- Transmission: The old transmission was very limiting on discrete viruses. Stealth symptoms are terrible at transmission and it was virtually impossible to counterbalance with the old system. Now you at least have a shot at fluid trnasmission. Still bad, but you can make smoke or splash it.
- Max resistance cure: Bicaridine? Really? Going through the trouble of …
> Virus tweaks

- _maps/RandomRuins/SpaceRuins/feeders_den.dmm
Does as the title says, all vendors in the feeder's den are free. Meaning no form of payment or bank account is required to use them anymore.
Ghost roles don't have bank accounts right now, it's nice for them to be able to use the vendors
:cl:
fix: Feeder's den vendors are now free
/:cl:
> Makes vendors in the Feeder's den free

- code/modules/mob/living/carbon/carbon_movement.dm
I accidentally set fat burned when moving to a positive number instead of a negative, this means that losing weight by moving around would cause you to gain weight.
You should be able to run from your weight
:cl:
fix: fixes weight being added when running due to the weight gain refactor. 
/:cl:
> Fixes issue with weight gain refactor

- GainStation13/code/clothing/calorite_collar.dm
- tgstation.dme
Adds in calorite collars to the game, regular collars "upgraded" with calorite, that increase the weight gain rate of the wearer if they have the item pref on.
These collars are craftable using the crafting menu and require a pet collar or a locked pet collar respectively 
I think this could provide some interesting options for gaining.
:cl:
add: Adds in calorite collars, collars that increase how fast weight is gained on the user.  
/:cl:
> Calorite Colllars

- code/game/objects/items/stacks/sheets/sheet_types.dm
Fixes double beds not being craftable
Big beds for big people
:cl:
fix: double beds are now craftable
/:cl:
> Fixes double beds not being craftable

- modular_citadel/code/modules/vore/eating/bellymodes_vr.dm
When digesting a prey with fatness, assuming that the weight gain from food pref is enabled, the pred will gain 80% of the fatness from the prey.
It makes sense for vore to have integrations with our fat system
:cl:
add: Fatal vore now has weight gain.
/:cl:
> Fatal vore now adds weight from digesting the prey

- code/modules/mob/dead/new_player/sprite_accessories/hair_head.dm
fixed two misnamed hairs
gives sonoida his gahdamn hair back. bald-ass.
:cl:
fix: long-gloomy and mohawk's improper icon-paths
/:cl:
> hair iconpath fix

- GainStation13/code/mechanics/wand.dm
- tgstation.dme
Adds in the wand of gluttony, a wand that spawns food with lipoifier under anything that it hits.
This is currently admin-spawn in only right now, as I'm not sure where I'd like to put this.
The wands use the default wand sprite, so if someone else would be interested in coding in a new sprite for them, I'd be happy to add it in.
More stuff to use for events is always good.
:cl:
add: Adds in the wand of gluttony, a wand that spawns lipoifier infused food under anything it hits.
/:cl:
> Adds in the wand of gluttony

- code/datums/diseases/advance/symptoms/weight.dm
Instead of using transmission for thresholds, the weight gain virus now uses stage speed.
I don't like needing to infect the entire station so that I can make a fattening virus that works well.
:cl:
balance: The weight gain virus symptom now uses stage speed instead of transmission.
/:cl:
> Weight Gain virus now uses stage speed instead of transmission

- code/__DEFINES/mobs.dm
- code/modules/mob/living/carbon/human/species.dm
- code/modules/mob/mob_movement.dm
Refactors the movement speed penalty added by weight gain. Weight added now gradually effects the movement speed instead of in stages like before. 
The weak legs trait has been changed so that instead of making the user completely immobile, it gives them an incredibly heavy movement speed penalty after getting past the blob stage.
This makes the code less pain to work with, and hopefully makes the weight gain system more enjoyable.
:cl:
refactor: refactors the movement speed penalities for weight gain
/:cl:
> Refactors the weight gain movement speed penalty

- code/game/objects/structures/statues.dm
Initially made to make the statue's messages work with the new fatness (Without writing more messages, but still.)
While there, I made a new unified proc to remove some duplicate code and changed beacon to beckon, as that seemed to match the proc's function better.
Helps people with shitty internet know that they are not lagging and that they did, in fact, click the statue. Also will be easier to modify in the future if someone really wants to write the four or so missing descriptions. Beckon was a bit of a nitpick though. Still, I think it helps clarity.
:cl:
fix: Calorite statue now has a message at any weight level.
refactor: Refactored the message choice.
refactor: The beacon proc is now beckon.
/:cl:
> Calorite statue fixes.

- GainStation13/code/modules/mob/living/emote.dm
- modular_citadel/code/modules/vore/eating/belly_obj_vr.dm
- modular_citadel/code/modules/vore/eating/living_vr.dm
Remove reverb from emotes and vore noises.
Remove duplicate vore eating noise on initial swallow.
Undo unwanted change and fix an annoying bug.
:cl: psq95
fix: Reverb on audible emotes
fix: Duplicate eating noise on vore swallow
/:cl:
> Fix emote noises

- code/__DEFINES/mobs.dm
- code/datums/traits/negative.dm
- code/datums/traits/neutral.dm
- code/modules/mob/living/carbon/human/species.dm
Changed weak legs to increase the slowdown from fat by 35% at all levels and practically immobile when immobile and heavier. As a result of it always being active it now has a -1 cost.
Previous weak legs was broken and didn't do what it was supposed to do it now works as intended. 
:cl: Fed09022
tweak: the effects of weak legs slowdown
fix: weak legs not making you immobile at very heavy weights
/:cl:
> Fixes to weak legs

- code/datums/datacore.dm
- code/modules/mob/living/carbon/life.dm
Add a new Status column to the Crew Manifest.
Allow new players, observers, and admins to see which current players are actually active.
The Crew Manifest is misleading when it displays a lot of people who are apparently active in the round but many or all may be inactive.
:cl: psq95
add: Add a new Status column to the Crew Manifest
/:cl:
> Add status to crew manifest

- code/modules/client/preferences.dm
- modular_citadel/code/modules/arousal/organs/genitals.dm
Belly: 1-12 -> 1-10
Butt: 0-5 -> 1-10
Butt actually has an extra sprite (11) but I think 1-10 for both is better for consistency.
Bring character setup in line with supported sprites.
:cl: psq95
fix: butt sprite range in char setup
/:cl:
> Adjust sprite ranges in char setup

- code/__DEFINES/dcs/signals.dm
- code/datums/elements/flavor_text.dm
- code/modules/client/preferences.dm
- code/modules/jobs/job_types/silicon.dm
- code/modules/mob/living/silicon/examine.dm
- code/modules/mob/living/silicon/robot/examine.dm
- code/modules/mob/living/silicon/silicon.dm
- code/modules/mob/transform_procs.dm
- modular_citadel/code/modules/client/preferences.dm
Propagate silicon examine text from client preferences to robot mob.
Only applies to Cyborg job role, not robotized "humans".
Also preserves newlines in all flavor text.
Features should work as intended.
Examine text is easier to read in lines than one long string.
:cl: psq95
fix: silicon examine text
/:cl:
> Fix Silicon Examine Text

- code/modules/mob/living/carbon/human/species.dm
Moved the min() function call to before the Strong Legs modifier is applied, if a character has it. This makes it so the trait has a tangible effect even at very high fatness, increasing its usefulness and making it a more worthwhile pick, while helping the roleplay of very fat characters who can still move relatively well, which is why the trait exists in the first place
> Strong Legs high weight fix

- GainStation13/code/modules/reagents/chemistry/reagents/fatty_drinks.dm
- code/modules/client/preferences.dm
- code/modules/mob/living/carbon/human/human_defines.dm
- code/modules/mob/living/carbon/human/species.dm
Hair gradients are now instanced as "None", the default no gradients value, rather than 000 which caused runtime newly instanced character to cause runtime errors. Fixed the path for the Beltbuster Mead drink's on_mob_life function
> Hair gradients fix and Beltbuster use fixed

- SQL/admin_import_2018-02-03.py
This pull request is intended to fix a minor, yet pretty annoying issue. If someone were to use an SQL server for their own testing build, and they wanted to import from admins.txt, while it works, Python has this nasty habit of whinging about how it was written. Namely saying:
"SyntaxWarning: "is" with 'str' literal. Did you mean "=="?"
Guh.
If there are rookies who are running this locally for testing or whatever, the warnings might put them off. Fixing that does mean that more testing can take place.
:cl:
refactor: Changing "is" to "==" so that python stops moaning.
/:cl:
> Correcting SQL Admin import script

- modular_citadel/code/modules/arousal/organs/genitals.dm
Added if to have the genital check if the owner exists when trying to update (skips the inventory update if not and updates the rest, so the body displays and updates correctly even if they are nude)
> Genitals update fix (again)

- code/game/machinery/doors/airlock.dm
- code/game/machinery/doors/door.dm
This change adds a failure count that increments each time a door attempts to close but something is blocking it. If it fails too many times, it simply stops trying. Doors can be closed manually once the blockage is removed.
Wooden barricades in powered airlocks cause lag as the doors try to autoclose over and over.
:cl: psq95
fix: Stop doors causing lag when blocked continuously
/:cl:
> Halt autoclose when blocked too many times

- GainStation13/code/obj/structure/scale.dm
Adds additional weight to taur characters when they go on scales. It's 2.5x for taur characters, meaning at 0 fatness a taur character will report a weight of 350 pounds while a non-taur character will report a weight of 140 pounds. Math was based on the assumption of a taur body adding at least 200 or so pounds (by default!), then making it multiplicative to imply the tauric half was also gaining weight.
I think it's strange that a taur who, at the same "fatness" as a non-taur character, will have the same weight, despite having an additional torso and even extra limbs. We already have a weight multiplier for people who scale their sprites, so I thought it would make sense to also have a multiplier for taurs. It might be useful to make it so that it differentiates between taur types (fat …
> Add additional weight to taur characters

- code/modules/food_and_drinks/kitchen_machinery/gibber.dm
Makes gibbers produce extra meat based on how fat the person getting turned into meat product is. 
This enables recycling meat from fat people who have gone SSD forever as well as allowing morally questionable fattening of livestock (crew members) and/or humanified monkies. It is also very funny to watch a lot of meat shoot out of the gibber. 
:cl:
add: Added extra meat comming out of the gibber when fat people get blended
/:cl:
> Makes putting fatties in the gibber produce more meat

- GainStation13/code/mobs/chocoslime.dm
- GainStation13/code/modules/client/preferences/preferences.dm
- code/__DEFINES/voreconstants.dm
- code/datums/traits/good.dm
- code/game/machinery/doors/airlock_types.dm
- code/modules/client/preferences.dm
- code/modules/client/preferences_savefile.dm
- code/modules/food_and_drinks/drinks/drinks.dm
- code/modules/food_and_drinks/food/snacks.dm
- code/modules/mob/living/carbon/human/species.dm
- modular_citadel/code/modules/vore/eating/belly_dat_vr.dm
- modular_citadel/code/modules/vore/eating/belly_obj_vr.dm
- modular_citadel/code/modules/vore/eating/bellymodes_vr.dm
- modular_citadel/code/modules/vore/eating/vorepanel_vr.dm
Added fatten vore belly mode. Adds 2% of predator's fatness to the preys, making them hungrier.
Fatten mode also uses fatness hiding to display the combined fatness of preys as the fatness of the predator while holding them in a fatten mode belly
Voracious trait now also modifies fullness added values to make the eater able to eat/drink twice as much. Also makes fullness decay twice as fast
Added stuckage pref, it and XWG are now under "GS13 Gameplay Preferences"
> Fatten mode vore. Voracious Trait fullness & Stuckage Preference

- code/modules/mob/living/carbon/damage_procs.dm
- code/modules/mob/living/carbon/human/species_types/jellypeople.dm
When jellypeople have reached the maximum blood level, any excess toxins will be turned into fatness.
Jellypeoplecapable of splitting can now do so using fatness (chosen first if there is both enough fatness and blood)
> Jellypeople toxins WG & Fatness Split

- GainStation13/code/modules/research/nanites/nanite_programs/fattening.dm
- code/__DEFINES/nanites.dm
- code/modules/research/nanites/nanite_programs/healing.dm
- code/modules/research/nanites/nanite_programs/sensor.dm
- code/modules/research/techweb/all_nodes.dm
- tgstation.dme
Fixed health-restoring nanite programs
Fixed Voice Sensor nanite programs
Added BFI Sensor and BFI Regulator nanite programs, found in the Biological Nanite Programming tech node. Sensor sends code if the host is above/under the specified amount of fatness, Regulator adds/removes the specified amount of fatness every activations, using up nanites.
> Nanites Fixes & BFI Nanites

- GainStation13/code/mechanics/fatness.dm
- GainStation13/code/modules/client/preferences/preferences.dm
- GainStation13/code/modules/research/nanites/nanite_programs/fattening.dm
- code/__DEFINES/misc.dm
- code/modules/client/preferences.dm
- code/modules/client/preferences_savefile.dm
This PR adds a preference that controls if nanites are able to fatten a player or not. Players can still lose weight through nanites.
Giving players more control is always good. This should also hopefully reduce the amount of OOC conversation needed when dealing with fattening nanites.
:cl:
add: Adds a preference for being fattened by nanites.
/:cl:
> adds prefs for nanite fattening

- code/modules/client/preferences.dm
- hyperstation/code/modules/resize/resizing.dm
Fixed being unbable to change one's breast fluid after selecting berry juice
Characters become unable to use things only over 200% size multiplier, not above 100%
> Berry juice breast fluid fix, Mob resize size tweak

- code/modules/food_and_drinks/recipes/tablecraft/recipes_misc.dm
The egg-plants peeling recipe didn't actually consume an egg-plant when used. Now it does. 
Hope people enjoyed the infinite eggs at least.
> Fixed Egg-Plants peeling recipe.

- code/modules/mining/equipment/explorer_gear.dm
Rebalances Mining Armors. 
Increases Explorer Suits melee defense by 5, giving it a total of 65% when fully upgraded, still lower than heavier options E.G. Mining hardsuit/Unique lavaland hardsuits.
Decreases Exo Suits melee defense to 50. Starts strong but gets outpaced by the Explorer Suit. Maintains Goliath stun resistance.
Remove SEVA Suits Goliath vulnerability trait. The suit already has low armor values, these are punishing enough for immediate storm-resistance.
> Rebalances mining armors

- code/modules/mining/machine_vending.dm
I've added the Explorer suit and mask to the suit voucher to be redeemed by miners.
Unifies selection process and gives Miners more immediate options when gearing up at the vendor
:cl:
fixed spelling mistake located within mining conscription suit dialog
added explorer suit and mask to suit redeem ticket
/:cl:
> added explorer suit to suit vendor redeem + spelling fix

- hyperstation/code/modules/client/loadout/gloves.dm
- hyperstation/code/modules/client/loadout/neck.dm
- hyperstation/code/modules/resize/resizing.dm
Brings all sizes more in line with eachother. Less buffs and debuffs all around. 
Makes normalizers free in the loadout screen, no reason they should be so expensive. Just remember to not take 2 or things break.
> Size rebalance

- _maps/RandomRuins/LavaRuins/lavaland_surface_duohermit.dmm
- _maps/RandomRuins/SpaceRuins/spacehermit.dmm
Woe. 
Omnilathes Upon Ye!
Gives Duo Lavaland and Space Hermits Omnilathes instead of Science Protolathes. 
Removes the random space suit added to the Space Hermits role, it's back to the original where the only suit is outside the asteroid.
> Upgrading Hermit Lathes.

- _maps/RandomZLevels/snowdin.dmm
- _maps/shuttles/snowdin_transit.dmm
- code/__DEFINES/access.dm
- code/datums/shuttles.dm
- code/game/objects/items/cards_ids.dm
- hyperstation/code/game/objects/structures/ghost_role_spawners.dm
Patches for Snowdin following the playtest that went really well and had no issues at all 👍 
Removed blood halberd (Forgot about this)
Re-added a DNA Manipulator, somewhere.
Made one of the surface dungeons more obvious. 
Reorganized the boards around the map. Easier to find.
No more station blueprints, all of you can't be trusted.
No more free food.
Transit Shuttle now appears as a map_template file (I forgor to merge shuttles.dm last time)
Transit Shuttle works! (Maybe)
More cards!
More Accesses!
More spawns!
Spawns now actually show up on the ghost role menu!
7 Spawns total, no more random outfits, each dorm has its own card and outfit in the closet.
> Snowdin patches

- GainStation13/code/modules/client/preferences/preferences.dm
- code/game/machinery/doors/airlock_types.dm
- code/game/objects/buckling.dm
- code/modules/client/preferences.dm
- code/modules/client/preferences_savefile.dm
Does as the title says.
more control good :3
:cl:
add: Chairs breaking under weight and getting stuck in doors are now controlled by prefs, functioning similarly to helplessness now.
/:cl:
> Makes chair breaking and door stuckage into weight dependant prefs

- .vscode/settings.json
- GainStation13/icons/obj/vairous_weapons.dm
- code/__DEFINES/combat.dm
- code/modules/mob/living/carbon/damage_procs.dm
- code/modules/mob/living/carbon/human/species.dm
- code/modules/mob/living/damage_procs.dm
- tgstation.dme
Adds a fattening damage type, allowing weapons to be instantly converted to do fattening damage.
think of the horrible things that the admins can make with this.
:cl:
add: Adds a fattening damage type, allowing for weapons to easily be converted into fattening weapons.
/:cl:
> Fattening Damage Type

- _maps/RandomZLevels/snowdin.dmm
- code/__DEFINES/access.dm
- code/modules/awaymissions/mission_code/snowdin.dm
- hyperstation/code/game/objects/structures/ghost_role_spawners.dm
Alright. Snowdin fixes round 2. 
Fixes missing areas.
Fixes shuttle (For real this time)
Fixes elevators working (Unintended)
Fixes the secret bear (working as intended)
Added a secret raid boss (God help us all)
Exile Spawns now show up in the ghost role menu. 
Added another ruin for more gear for explorers.
Add science accesses and give scientists the access
Gives Snowdin Captain actual all access to Snowdin
Gives engineering cards air alarm / apc access
Fixes incorrect floor tiles in cargo (DO NOT USE ENGINE/AIR WORST MISTAKE OF MY LIFE)
Fixes vents not working (Now with scrubbers, which do appear in the air alarm on my private)
Adds a hint as to where the botany gear has been taken too.
More medical stuff (medics got overwhelmed fast)
Netherworld Links no longer spawn 10 enemies
More …
> Snowdin patches round2

- code/game/machinery/quantum_pad.dm
fixes a bug that allows people to use the supply pad by hiding in crates.
:cl:
fix: fixes the supply supply pad teleporting people it shouldn't.
/:cl:
> fixes supply pad

- GainStation13/code/modules/food_and_drinks/food.dm
- GainStation13/code/modules/food_and_drinks/recipes/recipes_ported.dm
- code/modules/food_and_drinks/food/snacks_soup.dm
stupid idiot soup item isn't food :(
This fixes it, and also makes you able to recycle the mushroom bowl from it after it's eaten.
> Fixes Lavaland Stew not actually being soup.

- GainStation13/code/datums/mutations/fatfang.dm
- GainStation13/code/mechanics/fatness.dm
- GainStation13/code/mechanics/permanent_fat.dm
- GainStation13/code/modules/client/preferences/preferences.dm
- GainStation13/code/modules/reagents/chemistry/reagents/fermi_fat.dm
- code/__DEFINES/pool.dm
- code/__HELPERS/roundend.dm
- code/modules/client/preferences.dm
- code/modules/client/preferences_savefile.dm
- code/modules/mob/living/simple_animal/hostile/bees.dm
- modular_citadel/code/game/machinery/cryopod.dm
Permanent fat renamed to permanent weight
Added persistent fat. If enabled, it will save your character's real fatness at roundend or cryo as your new starting weight. Starting weight can still be tweaked from 0 to 8000 should you want to lose some of it.
Tweaked galbanic compound to behave better while addicted.
Macerinic solution can now be overdosed (50u). Overdosing causes your character to get hungry but also increases your weight loss rate up to 5
The Nibble mutation now allows you to bite yourself. The fangs no longer disappear after use, making drawing them out again needed, but remain in the hand. After an attack with them, you'll go into a 5 seconds melee cooldown. Internal change for admin memery, chem and amount injected can be changed as they are now tied to vars inside the …
> Permafat changes, Fatfang changes, Bees banned reagents

- code/game/objects/items/RCD.dm
- code/game/objects/items/RPD.dm
- code/game/objects/items/storage/belt.dm
- code/game/objects/items/tools/crowbar.dm
- code/game/objects/items/tools/screwdriver.dm
- code/game/objects/items/tools/wirecutters.dm
- code/game/objects/items/tools/wrench.dm
- tgstation.dme
- yogstation/code/game/objects/items/tools.dm
Makes all (most) belts bulky in size. This is a change bigger codebases made since it makes toolbelts a more dedicative item opposed to a weird box sidegrade. Toolbelts have been upgraded to allow storing RCDs, RPDs and other larger items. They also have a bit more storage space. Additionally, Durathread toolbelts have ~50% more space and ~40% more total items, to keep them as a strong upgrade. I might come back to this later and rebalance it. 
Did you know durathread toolbelts are like a combination of all 3 major department toolbelts? The description of the durathread toolbelt has been changed to reflect this, but it was a thing even before this PR.
Makes toolbelts a storage upgrade that's not in the same class as boxes. You gotta think about how you hold your stuffs now or someth,
also …
> Reworks toolbelts and upgrades engineer and durathread toolbelts

- code/__DEFINES/traits.dm
- code/modules/research/xenobiology/crossbreeding/_clothing.dm
- code/modules/research/xenobiology/crossbreeding/_status_effects.dm
- code/modules/research/xenobiology/crossbreeding/regenerative.dm
- code/modules/research/xenobiology/xenobiology.dm
- code/modules/vehicles/ridden.dm
Small nerfs to Xenobio, More will come
Nerfs adamantine armor to work as originally intended and reduces it's armor values further. (No more elite syndicate hardsuits)
Nerfs regenerative extracts (No more aheals, they instead add medicine too you on use TODO: Make a unique medicine for them to use since they should still be good)
Nerfs Stable Light Pink (Biggest offender is this thing. Makes you a pacifist when active, TG Change)
> Xenobiology nerf

- code/modules/reagents/chemistry/reagents/medicine_reagents.dm
- code/modules/research/xenobiology/crossbreeding/_status_effects.dm
- code/modules/research/xenobiology/crossbreeding/regenerative.dm
- code/modules/surgery/advanced/lobotomy.dm
Second round of nerfs to Xenobio
Adds a new chem for the regen extracts to use. Pure Regen Jelly and Pure Neo Jelly. Cannot be made in any way, heals rapidly and metabolizes slowly. 
Stable Purples cost hunger when in use now, high nutrition cost for low healing but Xenobiologists can produce food infinitely, and also just ask the chef for a framewrecker. They will stop healing you if you are starving
Yellow Stables now have a 30 second delay instead of 10 seconds, as before it could lead to infinite ammo laser guns really easily. 
Stable Dark Blue passively makes you colder now. You are soaking wet with them equipped after all and their main gimmick is killing fires automatically, which tend to make you hot.
> Xenobiology Nerf Round 2
